changes in css of landing page , and track page
All-About-Programming-Community/HackTheWinter-Official-Website pull request #2
Opened 2022-11-14 20:34 UTC by sanil011

2022-11-14 21:18 UTC, sanil011 commented
<img width="1440" alt="Screenshot 2022-11-15 at 2 47 15 AM" src="https://user-images.githubusercontent.com/105095685/201767404-1562f735-6f74-4e78-ba5d-291fcacbcf10.png">
<img width="1440" alt="Screenshot 2022-11-15 at 2 47 41 AM" src="https://user-images.githubusercontent.com/105095685/201767427-8bb4f800-d5e7-413d-b549-fb4c9a3b99c0.png">

2022-11-15 03:30 UTC, ank1traj reviewed
Remove `.lock` file

2022-11-15 04:38 UTC, sanil011 commented
> We should not have a `.lock.json`, please delete it

deleted..

2022-11-15 05:02 UTC, ank1traj commented
> > We should not have a `.lock.json`, please delete it
> 
> deleted..

`yarn.lock` file is still there @sanil011

2022-11-15 05:59 UTC, ank1traj approved these changes
LGTM

2022-11-15 06:22 UTC, sanil011 commented
> LGTM

okay , who will merge this??

2022-11-15 06:57 UTC, ank1traj commented
> > LGTM
> 
> okay , who will merge this??

You must have rights to do so.

2022-11-15 11:26 UTC, Suvraneel requested changes

2022-11-15 11:26 UTC, Suvraneel commented on pages/tracks.tsx
> +                </li>
Instead of redundant entries...
Please use the `.map` functionality to maintain D.R.Y format

2022-11-15 11:35 UTC, Suvraneel approved these changes
Since we're getting this done on priority, Imma make whatever changes needed before merging.
Also, I'll merge the PRs irrespective of approvals/requested changes as long as it maintains basic software architecture & follows principles of SOLID, DRY etc.

LGTM @sanil011

2022-11-15 11:35 UTC, merged